[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"

# Optimizer
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
verbosity = 2
gas_reports = ["OptionVault", "OptionToken", "OptionFactory"]
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Coverage
show_progress = true

# Formatter
line_length = 120
tab_width = 4
bracket_spacing = false

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 100 }

[profile.production]
optimizer_runs = 1000000
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
